### PR TITLE
Added Dijkstra algorithm

### PR DESCRIPTION
**Pull request by AkhileshManda**
Added dijkstra algorithm in java

### CODE REVIEW

**Comment by himakhaitan** [comment]
Can you please maintain the Readme along with it.

**Comment by AkhileshManda** [comment]
Do you mean create an algorithm section and update all algorithms?

**Comment by himakhaitan** [comment]
No, You Will Find a [Readme.md](https://github.com/himakhaitan/CP-Directory/blob/main/Algorithms/README.md) In Algorithms Folder. You need to update that. 
image

**Comment by AkhileshManda** [comment]
Done!

**Pull request merged**
